#!/usr/bin/env pwsh
# smart_switch.ps1 - Dynamic environment switcher with 33% admin reserve
# Run: ./smart_switch.ps1 -Mode auto

param(
    [ValidateSet("auto", "dev", "staging", "production")]
    [string]$Mode = "auto",
    [switch]$WithReserve,
    [string]$ReservePercent = "33"
)

Write-Host "🔄 SmartPrompt Elite - Dynamic Environment Switch" -ForegroundColor Cyan
Write-Host "══════════════════════════════════════════════════════════" -ForegroundColor Cyan

# Auto-detect environment
if ($Mode -eq "auto") {
    if (Get-Command vercel -ErrorAction SilentlyContinue) {
        $Mode = "production"
    } elseif (Test-Path ".env.development") {
        $Mode = "dev"
    } else {
        $Mode = "staging"
    }
}

Write-Host "📍 Selected Mode: $Mode" -ForegroundColor Green

# Load environment-specific config
$configs = @{
    dev = @{
        API_URL = "http://localhost:8080"
        WS_URL = "ws://localhost:8080"
        DATABASE_URL = "postgresql://localhost/smartprompt_dev"
        RESERVE_ENABLED = $true
        RESERVE_PERCENT = 33
        LOG_LEVEL = "debug"
        RATE_LIMIT = 1000
    }
    staging = @{
        API_URL = "https://staging.smartprompt.ai"
        WS_URL = "wss://staging.smartprompt.ai"
        DATABASE_URL = $env:STAGING_DB_URL
        RESERVE_ENABLED = $true
        RESERVE_PERCENT = 33
        LOG_LEVEL = "info"
        RATE_LIMIT = 5000
    }
    production = @{
        API_URL = "https://api.smartprompt.ai"
        WS_URL = "wss://api.smartprompt.ai"
        DATABASE_URL = $env:PROD_DB_URL
        RESERVE_ENABLED = $true
        RESERVE_PERCENT = 33
        LOG_LEVEL = "warn"
        RATE_LIMIT = 10000
    }
}

$config = $configs[$Mode]

# Update .env file
@"
# Auto-generated by smart_switch.ps1 - $(Get-Date)
NODE_ENV=$Mode
API_URL=$($config.API_URL)
WS_URL=$($config.WS_URL)
DATABASE_URL=$($config.DATABASE_URL)
RESERVE_ENABLED=$($config.RESERVE_ENABLED)
RESERVE_PERCENT=$($config.RESERVE_PERCENT)
LOG_LEVEL=$($config.LOG_LEVEL)
RATE_LIMIT=$($config.RATE_LIMIT)
ADMIN_RESERVE_WALLET=0xSmartPromptReserve
"@ | Out-File -FilePath ".env" -Encoding utf8

Write-Host "✅ Environment configured: .env" -ForegroundColor Green

# Start services based on mode
Write-Host "`n🚀 Starting services..." -ForegroundColor Yellow

switch ($Mode) {
    "dev" {
        Write-Host "🏠 Starting local development stack..."
        
        # Start Go backend
        Start-Process -NoNewWindow -FilePath "go" -ArgumentList "run backend/main.go"
        
        # Start Rust AI engine
        Start-Process -NoNewWindow -FilePath "./backend/sales_ai.exe" -RedirectStandardOutput "ai.log"
        
        # Start React frontend
        Start-Process -NoNewWindow -FilePath "npm" -ArgumentList "run dev"
        
        Write-Host "✅ Dev stack running:"
        Write-Host "   📡 API: http://localhost:8080"
        Write-Host "   🎨 Frontend: http://localhost:3000"
        Write-Host "   🧠 AI Engine: ai.log"
    }
    "staging" {
        Write-Host "🌙 Starting staging environment..."
        
        # Docker compose for staging
        docker-compose -f docker-compose.staging.yml up -d
        
        Write-Host "✅ Staging deployed"
    }
    "production" {
        Write-Host "🌍 Starting production deployment..."
        
        # Deploy to Vercel
        vercel --prod
        
        # Deploy Go backend to Google Cloud
        gcloud run deploy smartprompt-api --source ./backend
        
        Write-Host "✅ Production deployed"
    }
}

# Reserve distribution cron job
if ($config.RESERVE_ENABLED) {
    Write-Host "`n💰 Admin Reserve Active: $($config.RESERVE_PERCENT)% of all revenue" -ForegroundColor Magenta
    
    # Create scheduled task for reserve distribution (every 6 hours)
    $action = New-ScheduledTaskAction -Execute "python" -Argument "scripts/distribute_reserve.py"
    $trigger = New-ScheduledTaskTrigger -Once -At (Get-Date).AddHours(6) -RepetitionInterval (New-TimeSpan -Hours 6)
    Register-ScheduledTask -TaskName "SmartPromptReserve" -Action $action -Trigger $trigger -Force
    
    Write-Host "✅ Reserve distribution scheduled every 6 hours" -ForegroundColor Green
}

Write-Host "`n══════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "🎉 SmartPrompt Elite is LIVE!" -ForegroundColor Green
Write-Host "📊 Dashboard: $($config.API_URL)/dashboard" -ForegroundColor Cyan
Write-Host "🔑 Admin Reserve: $($config.RESERVE_PERCENT)%" -ForegroundColor Magenta
Write-Host "══════════════════════════════════════════════════════════" -ForegroundColor Cyan
